[pytest]
testpaths = tests

addopts =
    -ra
    --strict-markers
    --base-url=https://www.saucedemo.com
    --tracing=retain-on-failure
    --screenshot=only-on-failure
    --html=reports/report.html
    --self-contained-html
    -n 4

markers =
    smoke: Critical tests that must always pass
    negative: Tests using invalid or restricted input
    regression: Complete functional test suite